apiVersion: v2
name: bagisto
version: 0.1.0
description: A Helm chart for deploying Bagisto on Kubernetes
appVersion: "1.0.0"
dependencies:
- name: mysql
  version: 14.0.3
  repository: https://charts.bitnami.com/bitnami
  condition: mysql.enabled
- name: redis
  version: 24.1.2
  repository: https://charts.bitnami.com/bitnami
  condition: redis.enabled
