{{- if .Values.elasticsearch.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-elasticsearch
  labels:
    app: {{ include "bagisto.name" . }}-elasticsearch
spec:
  serviceName: {{ .Release.Name }}-elasticsearch
  replicas: {{ .Values.elasticsearch.replicas }}
  selector:
    matchLabels:
      app: {{ include "bagisto.name" . }}-elasticsearch
  template:
    metadata:
      labels:
        app: {{ include "bagisto.name" . }}-elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: "{{ .Values.elasticsearch.image }}:{{ .Values.elasticsearch.imageTag }}"
          ports:
            - containerPort: 9200
              name: http
            - containerPort: 9300
              name: transport
          env:
            - name: discovery.type
              value: "single-node"
            - name: xpack.security.enabled
              value: "false"
            - name: bootstrap.memory_lock
              value: "true"
            - name: ES_JAVA_OPTS
              value: {{ .Values.elasticsearch.esJavaOpts | quote }}
          resources:
            {{- toYaml .Values.elasticsearch.resources | nindent 12 }}
          volumeMounts:
            - name: elasticsearch-data
              mountPath: /usr/share/elasticsearch/data
          securityContext:
            capabilities:
              add:
                - IPC_LOCK
  volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes: {{ .Values.elasticsearch.volumeClaimTemplate.accessModes }}
        resources:
          requests:
            storage: {{ .Values.elasticsearch.volumeClaimTemplate.resources.requests.storage }}
{{- end }}
