apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bagisto-storage
spec:
  accessModes:
    - {{ .Values.storage.accessMode }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
  storageClassName: {{ .Values.storage.storageClassName | quote }}
