apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "bagisto.fullname" . }}-storage
  labels:
    app: {{ include "bagisto.name" . }}
spec:
  accessModes:
    - {{ .Values.storage.accessMode }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
  {{- if .Values.storage.storageClass }}
  storageClassName: {{ .Values.storage.storageClass }}
  {{- end }}
